version: "3.8"

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    shm_size: "512mb"
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./config/frigate:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/frigate:/media
      - ./data/frigate/database:/database
    ports:
      - "8971:8971"
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    networks:
      - homelab

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - homelab

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - FTLCONF_dns_listeningMode=all
    volumes:
      - ./etc-pihole:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    networks:
      - homelab

  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    hostname: homelab
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "host"
    volumes:
      - tailscale_data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_EXTRA_ARGS=--ssh
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /mnt:/srv
      - ./config/filebrowser/filebrowser.db:/database.db
    ports:
      - 8080:80
    environment:
      - PUID=0
      - PGID=0
    restart: unless-stopped
    networks:
      - homelab

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - kuma_data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    networks:
      - homelab

volumes:
  portainer_data:
  tailscale_data:
  kuma_data:

networks:
  homelab:
    driver: bridge
