version: "3.8"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - homelab

  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./config/frigate:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/frigate:/media
      - ./data/frigate/database:/database
    ports:
      - "8971:8971"
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    networks:
      - homelab
    labels:
      caddy: frigate.homelab.local
      caddy.reverse_proxy: "{{upstreams 8971}}"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - homelab
    labels:
      caddy: portainer.homelab.local
      caddy.reverse_proxy: "{{upstreams 9000}}"

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
    volumes:
      - pihole_etc:/etc/pihole
      - dnsmasq_etc:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks:
      - homelab
    labels:
      caddy: pihole.homelab.local
      caddy.reverse_proxy: "{{upstreams 80}}"

  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    hostname: homelab
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "host"
    volumes:
      - tailscale_data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_EXTRA_ARGS=--ssh
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  portainer_data:
  pihole_etc:
  dnsmasq_etc:
  tailscale_data:

networks:
  homelab:
    driver: bridge
