mqtt:
  enabled: true
  host: 192.168.0.180
  port: 1883
  user: mqtt
  password: mqtt
  topic_prefix: frigate
  client_id: frigate

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    stairs_hq:
      - rtsp://ha:homeassistant66@192.168.0.11:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:stairs_hq#audio=opus
    stairs_lq:
      - rtsp://ha:homeassistant66@192.168.0.11:554/cam/realmonitor?channel=1&subtype=2
    front_hq:
      - rtsp://ha:homeassistant66@192.168.0.13:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:front_hq#audio=opus
    front_lq:
      - rtsp://ha:homeassistant66@192.168.0.13:554/cam/realmonitor?channel=1&subtype=2
    side_hq:
      - rtsp://ha:homeassistant66@192.168.0.12:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:side_hq#audio=opus
    side_lq:
      - rtsp://ha:homeassistant66@192.168.0.12:554/cam/realmonitor?channel=1&subtype=2
    # t1_hq:
    #   - rtsp://ha:homeassistant66@192.168.0.14:554/cam/realmonitor?channel=1&subtype=0
    # t1_lq:
    #   - rtsp://ha:homeassistant66@192.168.0.14:554/cam/realmonitor?channel=1&subtype=2
    back_hq:
      - rtsp://ha:homeassistant66@192.168.0.15:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:side_hq#audio=opus
    back_lq:
      - rtsp://ha:homeassistant66@192.168.0.15:554/cam/realmonitor?channel=1&subtype=2
    garage_bel_hq:
      - ffmpeg:http://192.168.0.123/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=ha&password=homeassistant66#video=copy#audio=copy#audio=opus
      - rtsp://ha:homeassistant66@192.168.0.123:554/Preview_01_sub
    garage_bel_lq:
      - ffmpeg:http://192.168.0.123/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=ha&password=homeassistant66
    voordeur_bel_hq:
      - ffmpeg:http://192.168.0.229/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=ha&password=homeassistant66#video=copy#audio=copy#audio=opus
      - rtsp://ha:homeassistant66@192.168.0.229:554/Preview_01_sub
    voordeur_bel_lq:
      - ffmpeg:http://192.168.0.229/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=ha&password=homeassistant66
  webrtc:
    candidates:
      - 192.168.0.199:8555
      - stun:8555

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
cameras:
  # t1:
  #   enabled: true
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/t1_hq
  #         roles:
  #           - record
  #       - path: rtsp://localhost:8554/t1_lq
  #         roles:
  #           - detect
  camera_garage_bel:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage_bel_hq
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/garage_bel_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask: 0.28,0,0.277,0.072,0.703,0.07,0.703,0
    zones:
      garage_bel:
        coordinates: 0.476,0.647,0.821,0.63,0.839,0.534,1,0.522,0.996,0.997,-0.002,0.997,0.001,0.222,0.109,0.246,0.093,0.451,0.356,0.497
        loitering_time: 0
    review:
      alerts:
        required_zones: garage_bel
  camera_deur_bel:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/voordeur_bel_hq
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/voordeur_bel_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
  camera_back:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/back_hq
          roles:
            - record
        - path: rtsp://localhost:8554/back_lq
          roles:
            - detect
    zones:
      back_garden:
        coordinates: 0.804,0.139,0.531,0.094,0.336,0.206,0.423,0.405,0.275,0.511,0.172,0.666,0.137,0.994,0.9,0.993
        loitering_time: 0
        objects: person
        inertia: 3
    motion:
      mask: 0.003,0.377,0.527,0.081,0.995,0.152,0.995,0.008,0.002,0.006
  camera_stairs:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/stairs_hq
          roles:
            - record
        - path: rtsp://localhost:8554/stairs_lq
          roles:
            - detect
    zones:
      stairs:
        coordinates: 0.307,0.38,0.344,0.616,0.404,0.664,0.457,0.663,0.486,0.682,0.29,1,0.001,0.999,0,0.299,0.145,0.456,0.241,0.403
        loitering_time: 0
        inertia: 3
        objects: person
    motion:
      mask: 0.639,0,0.637,0.14,1,0.159,1,0
      threshold: 55
      contour_area: 10
      improve_contrast: "true"
    review:
      alerts:
        required_zones: stairs
    objects:
      mask: 0.281,0.671,0.335,0.692,0.336,0.756,0.281,0.749
  camera_front:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/front_hq
          roles:
            - record
        - path: rtsp://localhost:8554/front_lq
          roles:
            - detect
    motion:
      mask: 0.552,0,0,0,0,0.106,0,0.536,0.152,0.232,0.554,0.091,1,0.391,1,0
      threshold: 40
      contour_area: 10
      improve_contrast: "true"
    zones:
      front_garden:
        coordinates: 0.197,0.235,0.265,0.224,0.361,0.169,0.384,0.261,0.668,0.492,0.516,0.994,0.284,0.994,0.243,0.682,0.187,0.362
        inertia: 3
        loitering_time: 0
      front_door:
        coordinates: 0.162,0.271,0.298,0.274,0.532,0.449,0.218,0.597
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones:
          - front_garden
          - front_door
    objects:
      mask: 0.587,0.19,0.75,0.216,0.738,0.499,0.584,0.419
  camera_side:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/side_hq
          roles:
            - record
        - path: rtsp://localhost:8554/side_lq
          roles:
            - detect
    motion:
      mask: 0.236,0,0.583,0,1,0,1,0.166,0.386,0.097
      threshold: 40
      contour_area: 10
      improve_contrast: "true"
    zones:
      side:
        coordinates: 0.421,0.185,0.61,0.245,0.664,0.244,0.711,0.183,0.819,0.172,0.851,0.479,0.998,0.991,0,1,0,0.68,0.041,0.317,0.21,0.205
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: side
