services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./config:/www/assets
    ports:
      - 8083:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped
