services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    shm_size: "512mb"
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./config.yml:/config/config.yml
      - /etc/localtime:/etc/localtime:ro
      - /media/frigate:/media/frigate
      - ./data/frigate/database:/database
    ports:
      - "8971:8971"
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate.rule=Host(`frigate.ewaldbervoets.com`)"
      - "traefik.http.routers.frigate.entrypoints=websecure"
      - "traefik.http.routers.frigate.tls.certresolver=letsencrypt"
      - "traefik.http.services.frigate.loadbalancer.server.port=8971"
      - "traefik.http.services.frigate.loadbalancer.server.scheme=https"
      - "traefik.http.services.frigate.loadbalancer.server.insecureSkipVerify=true"

networks:
  homelab:
    external: true
